### ISSUE TITLE
Task L3.2.1: Métricas de Proceso Ágil y Recursos (L2/L3) 

### ISSUE THREAD

**Issue by DavidGananGarcia** [gii-is-psg2/PSG2-1920-G5-51#40]
En principio, este apartado lo vamos a poner como una tarea, si tuviera más complejidad o mayor longitud de la que esperábamos, lo cambiaremos y la dividiremos en dos subtareas.

**Comment by jossanrui5** [comment]
David: L2
Stefan: L3
